name: Build Releases

on:
  workflow_dispatch:
  push:

env:
  THIS_REF: ${{ github.ref }}
  BACKEND_REF_DEFAULT: master
  FRONTEND_REF_DEFAULT: master

permissions:
  contents: read

jobs:
  run-build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version: ['3.14']
        build-target:
          # TODO: Uncomment
          # - "windows_amd64"
          - 'linux_amd64'
          # - "linux_arm64"
          # - "darwin_amd64"
          # - "darwin_arm64"
          # - "freebsd_amd64"
          # - "freebsd_arm64"

    steps:
      # checkout this repo
      - name: checkout root repo
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.THIS_REF }}
          fetch-depth: 0
          path: 'src/certwarden'

      # checkout backend
      - name: checkout backend repo
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/certwarden-backend
          # ref: to be set later
          fetch-depth: 0
          path: 'src/certwarden-backend'

      # checkout backend to the correct ref
      # use release version if THIS_REF is formatted as "v#.#.#", else try branch name, else use default
      - name: checkout backend to correct ref
        working-directory: 'src/certwarden-backend'
        run: |
          if [[ ${{ env.THIS_REF }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              git checkout "${{ env.THIS_REF }}"
          elif git ls-remote --exit-code origin "${{ github.head_ref || github.ref_name }}"; then
              git checkout "${{ github.head_ref || github.ref_name }}"
          else
              git checkout "${{ env.BACKEND_REF_DEFAULT }}"
          fi

      # checkout frontend and select correct ref
      - name: checkout frontend repo
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/certwarden-frontend
          # ref: to be set later
          fetch-depth: 0
          path: 'src/certwarden-frontend'

      - name: checkout frontend to correct ref
        working-directory: 'src/certwarden-frontend'
        run: |
          if [[ ${{ env.THIS_REF }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              git checkout "${{ env.THIS_REF }}"
          elif git ls-remote --exit-code origin "${{ github.head_ref || github.ref_name }}"; then
              git checkout "${{ github.head_ref || github.ref_name }}"
          else
              git checkout "${{ env.FRONTEND_REF_DEFAULT }}"
          fi

      # setup build environment
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'src/certwarden-backend/go.mod'
          cache-dependency-path: 'src/certwarden-backend/go.sum'

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: 'src/certwarden-frontend/.node-version'
          cache: 'npm'
          cache-dependency-path: 'src/certwarden-frontend/package-lock.json'

      - name: get pkgs
        working-directory: 'src/certwarden-frontend'
        run: npm ci

      - name: Build using build script
        working-directory: 'src/certwarden'
        run: python build.py ${{ matrix.build-target }} --gitrequired

      - name: save build release
        uses: actions/upload-artifact@v7
        with:
          name: certwarden-${{ matrix.build-target }}
          path: '/src/certwarden/_out/certwarden-*_${{ matrix.build-target }}.*'
